### PR TITLE
add musdb18 dataset

### PR DESCRIPTION
**Pull request by faroit**
we have a new iteration of the dsd100 dataset encoded as stems.

### CODE REVIEW

**Comment by ybayle** [comment]
@faroit Thank you for your contribution.
Yet, I have to precise that the file [datasets.md](https://github.com/ybayle/awesome-deep-learning-music/blob/master/datasets.md) you modified is automatically generated by the python script [dl4m.py](https://github.com/ybayle/awesome-deep-learning-music/blob/master/dl4m.py) that parse [dl4m.bib](https://github.com/ybayle/awesome-deep-learning-music/blob/master/dl4m.bib). The file [dl4m.bib](https://github.com/ybayle/awesome-deep-learning-music/blob/master/dl4m.bib) references articles and corresponding datasets that were used by deep learning experiments. To guarantee consistency of this repo, it seems preferable to wait for an article to use the dataset musdb18 before adding it to [datasets.md](https://github.com/ybayle/awesome-deep-learning-music/blob/master/datasets.md). If you already have such an article, please tell me or add it to [dl4m.bib](https://github.com/ybayle/awesome-deep-learning-music/blob/master/dl4m.bib) following the [guidelines](https://github.com/ybayle/awesome-deep-learning-music/blob/master/CONTRIBUTING.md).

Additionally, you could add your dataset to:
- http://www.audiocontentanalysis.org/data-sets/
- https://github.com/caesar0301/awesome-public-datasets

**Comment by faroit** [comment]
> To guarantee consistency of this repo, it seems preferable to wait for an article to use the dataset musdb18 before adding it to datasets.md.

cool, makes sense... first citations will come in february. 
On the other hand we have registered that dataset with a separate DOI this time, so maybe we just add this to the references? Or would this destroy your automatic stats?

```
@misc{rafii_zafar_2017_1117372,
  author       = {Rafii, Zafar and
                  Liutkus, Antoine and
                  Fabian-Robert Stöter and
                  Mimilakis, Stylianos Ioannis and
                  Bittner, Rachel},
  title        = {musdb18},
  month        = dec,
  year         = 2017,
  doi          = {10.5281/zenodo.1117372},
  url          = {https://doi.org/10.5281/zenodo.1117372}
}
```

**Comment by ybayle** [comment]
> first citations will come in february.

This sounds in line with the aim of this repo that is to keep track of deep learning methods applied to music. If you already have an arxiv version of your paper you can manually add it to [dl4m.bib](https://github.com/ybayle/awesome-deep-learning-music/blob/master/dl4m.bib) and your database will be automatically added and referenced in the [datasets.md](https://github.com/ybayle/awesome-deep-learning-music/blob/master/datasets.md) file.

**Comment by faroit** [comment]
Okay, if its okay, I would keep this PR open as a reminder for me ;-)

**Comment by faroit** [comment]
@ybayle Okay, so the first citations are up: https://scholar.google.com/scholar?cites=4118090930914015738&as_sdt=2005&sciodt=0,5&hl=en and chances are that musdb18 will be the most used source separation dataset very soon.

Now, you have decide if you want to add the [SiSEC Paper](https://arxiv.org/abs/1804.06267) or the zenodo DOI as mentioned above. Just tell me what you like and I can add a PR.

**Comment by ybayle** [comment]
Hi @faroit do you consider MUSDB18 i) a new iteration of the dsd100 dataset or ii) a completely different dataset?
- If i) then it would be better to add two links to all reference to the DSD100 dataset: the old v1 and the new v2 represented by MUSDB18.
- If ii) then to be in line with the way the repo works now, the only way to have the dataset referenced is to add an article that uses deep learning methods applied to this MUSDB18 (e.g. https://arxiv.org/pdf/1806.03185.pdf). N.B.: Please refer to the [CONTRIBUTING.md](CONTRIBUTING.md) file to do this.
- If you consider both are valid assumptions then both should be done ideally.

> Now, you have decide if you want to add the SiSEC Paper or the zenodo DOI as mentioned above.

Currently the zenodo link gives a `DOI Not Found`. In the meantine the SiSEC Paper link can be used.

Thanks for your help and your contribution!

**Comment by faroit** [comment]
> Hi @faroit do you consider MUSDB18 i) a new iteration of the dsd100 dataset or ii) a completely different dataset?

well, its all based on MSD (not million song dataset) but was iteratively increased in size. It would be nice if DSD/MUS would appear aggregated in one of the plots.
so what about aggregating DSD100 and and MUSDB18 to DSD/MUSDB for all entries?

> Currently the zenodo link gives a DOI Not Found. In the meantine the SiSEC Paper link can be used.

can you [try again](https://doi.org/10.5281/zenodo.1117372)?

**Comment by ybayle** [comment]
> > Currently the zenodo link gives a DOI Not Found. In the meantine the SiSEC Paper link can be used.

> can you [try again](https://doi.org/10.5281/zenodo.1117372)?

This new link works for me.

> so what about aggregating DSD100 and and MUSDB18 to DSD/MUSDB for all entries?

This could lead people to think that one given article used all the songs from MUSDB18. This is not always true.
So what about adding a link on the [DSD100 dataset page](http://sisec17.audiolabs-erlangen.de/#/dataset) that indicates it now belongs to the MUSDB project and that the later should be prefered?

> well, its all based on MSD (not million song dataset) but was iteratively increased in size. It would be nice if DSD/MUS would appear aggregated in one of the plots.

It could also be considered to add for every dataset the "stem cell" dataset where the songs come from, e.g. for DSD100 it would be MSD and for MUSDB18 it would be DSD100.

**Comment by ybayle** [comment]
Hi @faroit do you have an update on this PR?

**Comment by ybayle** [comment]
Hi @faroit do you have an update on this PR?

**Comment by faroit** [comment]
not sure whats left to do. I think we should just stick with adding `MUSDB18` as a dataset. DSD100 and MSD is deprecated and shouldn't be used by the community

**Comment by ybayle** [comment]
> not sure whats left to do. I think we should just stick with adding `MUSDB18` as a dataset. DSD100 and MSD is deprecated and shouldn't be used by the community

Ok, thanks for the info! So it's done in the last commit: https://github.com/ybayle/awesome-deep-learning-music/commit/b252aaf8d441173d4b23bcdd184f2d2fcd61d7cb

**Comment by faroit** [comment]
@ybayle 6 years later. GitHub never forgets :)

**Comment by ybayle** [comment]
> @ybayle 6 years later. GitHub never forgets :)

@faroit better late than never ;) 
I just updated it because I saw some more activity and that people are still staring it and using it. For a small PhD project I did a long time ago that seems to help some people, that's good.
It still relevant but not complete with the newest article. Hopefully one day, someone will add the latest ref!

**Pull request closed without merging**
